services:
  etl-clickhouse-server:
    image: yandex/clickhouse-server:20.3.19.4
    container_name: etl-clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./database:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
