services:
  server:
    image: gitea/gitea:1.22.1
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
