services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    environment:
      - VERDACCIO_PORT=4873
    volumes:
      - './storage:/verdaccio/storage'
      - './config:/verdaccio/conf'
      - './plugins:/verdaccio/plugins'
    network_mode: host