services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API 端口
      - "9001:9001"  # MinIO 控制台端口
    volumes:
      - ./data:/data  # 绑定主机目录作为存储目录
    environment:
      - MINIO_ROOT_USER=admin  # 设置 MinIO 管理员用户名
      - MINIO_ROOT_PASSWORD=admin123  # 设置 MinIO 管理员密码
    command: server /data --console-address ":9001"